export const reportSelectors = {
    clientReportURL: 'a[href="/client-report"]',
    DateDropdown : '.MuiSelect-root',
    clientSelector : 'input[id^="client"]',
    companySelector : 'input[id="companies"]',
    clientTypeSelector:'.MuiInputBase-inputAdornedEnd:eq(7)',
    tagSelector:'.MuiInputBase-inputAdornedEnd:eq(9)',
    filterButton : '[tabindex="0"][type="button"] > .MuiButton-label:eq(0)',
    dateRangeButton : '.MuiSwitch-input:eq(0)',
    dateFromSelector : 'input[id^="date-picker-"]:eq(0)',
    dateToSelector : 'input[id^="date-picker-"]:eq(1)',
    eventFilterButton : 'button[class="MuiButtonBase-root MuiIconButton-root MuiAutocomplete-popupIndicator"]:eq(0)',
    userFilterButton : 'button[class="MuiButtonBase-root MuiIconButton-root MuiAutocomplete-popupIndicator"]:eq(1)',
    eventFilterSelected : 'div.MuiChip-deletableColorPrimary',
    eventFilterText : ':nth-child(2) > .MuiListItemText-root > .MuiListItemText-primary > span',
    removeFilter : '.MuiChip-root > .MuiSvgIcon-root > path',
    deleteClient : '.MuiAutocomplete-clearIndicatorDirty:eq(0)',
    deleteCompany : '.MuiAutocomplete-clearIndicatorDirty:eq(1)',
    deleteClientType : '.MuiAutocomplete-clearIndicatorDirty:eq(3)',
    deleteTag : '.MuiAutocomplete-clearIndicatorDirty:eq(5)',
    reportTab : 'button.MuiTab-textColorPrimary:eq(0)',
    newTab : 'button.MuiTab-textColorPrimary:eq(1)',
    deliveredTab : 'button.MuiTab-textColorPrimary:eq(2)',
    completedTab : 'button.MuiTab-textColorPrimary:eq(3)',
    reworkNeededTab : 'button.MuiTab-textColorPrimary:eq(5)',
    rejectedTab : 'button.MuiTab-textColorPrimary:eq(6)',
    agingTab : 'button.MuiTab-textColorPrimary:eq(7)',
    weeklyTab : 'button.MuiTab-textColorPrimary:eq(8)',
    deadlineTab : 'button.MuiTab-textColorPrimary:eq(9)',
    QAErrorsTab : 'button.MuiTab-textColorPrimary:eq(10)',
    commentFilterButton : '[tabindex="0"][type="button"] > .MuiButton-label:eq(7)',
    artistCompanySelector : 'input[id="artist_co"]',
    issueResolvedCheckbox : 'input[type="checkbox"]:eq(0)',
    issueNotResolvedCheckbox : 'input[type="checkbox"]:eq(1)',
    selectComplexity : '#complexitiesDic',
    bonusReportSelector : '#artist_co',

}