export const registrationSelectors = {  
    email : '#index_email',
    password : '#password',
    confirmPassword : '#passwordConfirm',
    agreeCheck : '#agree',
    signUpBtn : '#btn-signup',
    rememberMeCheck : '#remember',
    topBanner : '[class="MuiGrid-root MuiGrid-container"]',
    firstName : '[class="MuiInputBase-input MuiOutlinedInput-input"]:eq(0)',
    lastName : '[class="MuiInputBase-input MuiOutlinedInput-input"]:eq(1)',
    companyName : '[class="MuiInputBase-input MuiOutlinedInput-input"]:eq(2)',
    phoneNumber : '[class="MuiInputBase-input MuiOutlinedInput-input"]:eq(3)',
    billingFirstName : '#first_name',
    billingLastName : '#last_name',
    street : '#street_address',
    city : '#city',
    province : '#state',
    country : '#mui-component-select-country',
    zipCode : '#zip_code',
    saveBillings : '#save_billing_details',
    cardNumber : 'input[name="cardnumber"]',
    expiry : 'input[name="exp-date"]',
    cvv: 'input[name="cvc"]',
    isTerms: '#agree_terms',
    isPromotion: '#agree_mailing',
}