export const homePageSelectors = {
    createModelBtn: 'button[class*="MuiButtonBase-root MuiButton-root MuiButton-contained"]',
    contactUdBtn : 'button[class*="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary"]',
    /** Support Dialog Selectors */ 
    supportDialog : 'div[data-garden-container-id="focusjail"]',
    widgetHeader : 'header[data-testid="widget-header-view"]',
    minimiseBtn : '[data-garden-id="buttons.icon_button"]',
    supportDialogForm : '[data-testid="support-ticket-form"]',
    formField : '[data-garden-id="forms.field"]',
    textInput : '[data-garden-id="forms.input"]',
    textAreaInput : '[data-garden-id="forms.textarea"]',
    attachBtn : '#dropzone-input',
    attachFileInstruction : '#attachmentButtonDescription',
    sendBtn : '[data-garden-id="buttons.button"]',
    firstNameLabel : '#label-firstname-9596aeea-8cde-4dcf-b26b-93d3d76abeb9',
    firstNameText : 'input[name="firstname"]',
    lastNameLabel : '#label-lastname-9596aeea-8cde-4dcf-b26b-93d3d76abeb9',
    lastNameText : 'input[name="lastname"]',
    emailLabel : '#label-email-9596aeea-8cde-4dcf-b26b-93d3d76abeb9',
    emailText : 'input[name="email"]',
    messageLabel : '#label-message-9596aeea-8cde-4dcf-b26b-93d3d76abeb9',
    messageText : 'textarea[name="message"]',
    legalConsentLabel : 'input[name="LEGAL_CONSENT.subscription_type_11783728"]',
    submitButton : 'input[type="submit"]',
    form9MandatoryErrorMessage1: 'label[class="hs-error-msg hs-main-font-element"]',
    form9MandatoryErrorMessage2: 'label[class="hs-main-font-element"]',
}